<?php
/* vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4: */
/**
 * Ranking2chWatcherTest
 * PHPUnit用のテストクラス
 *
 * @package		Ranking2chWatcher
 * @author		松井 健太郎 (Kentaro Matsui) <info@ke-tai.org>
 * @copyright	ke-tai.org
 * @license		BSD
 * @see			http://2ch-ranking.net/api.html
 **/

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-24 at 16:07:04.
 */
class Ranking2chWatcherTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Ranking2chWatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		ob_start();
		require_once '../Ranking2chWatcher.php';
		ob_end_clean();
        $this->object = new Ranking2chWatcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ranking2chWatcher::run
     */
    public function testRun()
    {
		ob_start();
		$ret = $this->object->run();
		$output = ob_get_contents();
		ob_end_clean();
		$this->assertNull($ret);
		$this->assertNotNull($output);
		$this->assertNotEmpty($output);
    }

    /**
     * @covers Ranking2chWatcher::getThreadList
     */
    public function testGetThreadList()
    {
		$thread_list = $this->object->getThreadList();
		$this->assertNotNull($thread_list);
		$this->assertNotEmpty($thread_list);
		$this->assertFalse(!json_decode($thread_list));
    }

    /**
     * @covers Ranking2chWatcher::getForces
     */
    public function testGetForces()
    {
		$thread_list = $this->object->getThreadList();
		
		// キーワードにマッチする場合
		$ret_match = $this->object->getForces($thread_list, '/.*/');
		$this->assertNotNull($ret_match);
		$this->assertNotEmpty($ret_match);
		$this->assertRegExp('/^[0-9]+$/', $ret_match);
		
		// キーワードにマッチしない
		$ret_no_match = $this->object->getForces($thread_list, '/^$/');
		$this->assertNotNull($ret_no_match);
		$this->assertEquals(0, $ret_no_match);
    }
}
